version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: test-pw
      POSTGRES_USER: test-user
      POSTGRES_DB: baseterm
    hostname: baseterm-pg-instance
    networks:
      - baseterm-e2e-tests-net

  pg-migrations:
    image: baseterm-api:dev
    depends_on:
    - db
    environment:
      DATABASE_URL: postgres://test-user:test-pw@baseterm-pg-instance:5432/baseterm
      APP_ENV: dev
    entrypoint: [
      "./wait-for-it/wait-for-it.sh",
      "baseterm-pg-instance:5432", 
      "--", 
      "npm", 
      "run", 
      "migrate", 
      "up"
    ]
    networks:
      - baseterm-e2e-tests-net

  baseterm-api:
    image: baseterm-api:dev
    depends_on:
      pg-migrations:
         condition: service_completed_successfully
    environment:
      DATABASE_URL: postgres://test-user:test-pw@baseterm-pg-instance:5432/baseterm
      APP_ENV: dev
      AUTH_SECRET: killjoy
      PORT: 4000
    hostname: baseterm-api
    networks:
      - baseterm-e2e-tests-net

  test-runner:
    image: baseterm-api:dev
    depends_on:
    - baseterm-api
    environment:
      AUTH_SECRET: killjoy
    networks:
      - baseterm-e2e-tests-net
    entrypoint: [
      "./wait-for-it/wait-for-it.sh",
      "baseterm-api:4000",
      "--",
      "npm",
      "exec",
      "--",
      "jest",
      "--coverage",
      "--testMatch=**/tests/e2e-tests/**/*.test.ts"
    ]
    
networks:
  baseterm-e2e-tests-net:
    driver: bridge
    name: baseterm-e2e-tests-net
